import random as rn
import os
englishWords = ['ability', 'able', 'abroad', 'accept', 'accident', 'according to', 'achieve', 'act', 'active', 'actually', 'adult', 'advantage', 'adventure', 'advertise', 'advertisement', 'advertising', 'affect', 'after', 'against', 'ah', 'airline', 'alive', 'all', 'all right', 'allow', 'almost', 'alone', 'along', 'already', 'alternative', 'although', 'among', 'amount', 'ancient', 'angrily', 'ankle', 'any', 'any more', 'anybody', 'anyway', 'anywhere', 'app', 'appear', 'appearance', 'apply', 'architect', 'architecture', 'argue', 'argument', 'army', 'arrange', 'arrangement', 'as', 'asleep', 'assistant', 'athlete', 'attack', 'attend', 'attention', 'attractive', 'audience', 'author', 'available', 'average', 'avoid', 'award', 'awful', 'back', 'background', 'badly', 'bar', 'baseball', 'based', 'basketball', 'bean', 'bear', 'beat', 'beef', 'before', 'behave', 'behaviour', 'belong', 'belt', 'benefit', 'best', 'better', 'between', 'billion', 'bin', 'biology', 'birth', 'biscuit', 'bit', 'blank'
,'blood', 'blow', 'board', 'boil', 'bone', 'book', 'borrow', 'boss', 'bottom', 'bowl', 'brain', 'bridge', 'bright', 'brilliant', 'broken', 'brush', 'burn', 'businessman', 'button', 'camp', 'camping', 'can', 'care', 'careful', 'carefully', 'carpet', 'cartoon', 'case', 'cash', 'castle', 'catch', 'cause', 'celebrate', 'celebrity', 'certain', 'certainly', 'chance', 'character', 'charity', 'chat', 'check', 'chef', 'chemistry', 'chip', 'choice', 'church', 'cigarette', 'circle', 'classical', 'clear', 'clearly', 'clever', 'climate', 'close', 'closed', 'clothing', 'cloud', 'coach', 'coast', 'code', 'colleague', 'collect', 'column', 'comedy', 'comfortable', 'comment', 'communicate', 'community', 'compete', 'competition', 'complain', 'completely', 'condition', 'conference', 'connect', 'connected', 'consider', 'contain', 'context', 'continent', 'continue', 'control', 'cook', 'cooker', 'copy'
,'corner','correctly', 'count', 'couple', 'cover', 'crazy', 'creative', 'credit', 'crime', 'criminal', 'cross', 'crowd', 'crowded', 'cry', 'cupboard', 'curly', 'cycle', 'daily', 'danger', 'dark', 'data', 'dead', 'deal', 'dear', 'death', 'decision', 'deep', 'definitely', 'degree', 'dentist', 'department', 'depend', 'desert', 'designer', 'destroy', 'detective', 'develop', 'device', 'diary', 'differently', 'digital', 'direct', 'direction', 'director', 'disagree', 'disappear', 'disaster', 'discover', 'discovery', 'discussion', 'disease', 'distance', 'divorced', 'document', 'double', 'download', 'downstairs', 'drama', 'drawing', 'dream', 'drive', 'driving', 'drop', 'drug', 'dry', 'earn', 'earth', 'easily', 'education', 'effect', 'either', 'electric', 'electrical', 'electricity', 'electronic', 'employ', 'employee', 'employer', 'empty', 'ending', 'energy', 'engine', 'engineer', 'enormous', 'enter', 'environment', 'equipment', 'error', 'especially', 'essay', 'everyday', 'everywhere', 'evidence', 'exact', 'exactly', 'excellent', 'except', 'exist',
'expect', 'experience', 'experiment', 'expert', 'explanation', 'express', 'expression', 'extreme', 'extremely', 'factor', 'factory', 'fail', 'fair', 'fall', 'fan', 'farm', 'farming', 'fashion', 'fat', 'fear', 'feature', 'feed', 'female', 'fiction', 'field', 'fight', 'figure', 'film', 'final', 'finally', 'finger', 'finish', 'first', 'firstly', 'fish', 'fishing', 'fit', 'fix', 'flat', 'flu', 'fly', 'flying', 'focus', 'following', 'foreign', 'forest', 'fork', 'formal', 'fortunately', 'forward', 'free', 'fresh', 'fridge', 'frog', 'fun', 'furniture', 'further', 'future', 'gallery', 'gap', 'gas', 'gate', 'general', 'gift', 'goal', 'god', 'gold', 'golf', 'good', 'government', 'grass', 'greet', 'ground', 'guest', 'guide', 'gun', 'guy', 'habit', 'half', 'hall', 'happily', 'have', 'headache', 'heart', 'heat', 'heavy', 'height', 'helpful', 'hero', 'hers', 'herself', 'hide', 'high', 'hill', 'himself', 'his', 'hit', 'hockey', 'hold', 'hole', 'home', 'hope', 'huge', 'human', 'hurt', 'ideal', 'identify', 'ill', 'illness', 'image', 'immediately', 'impossible', 'included', 'including', 'increase', 'incredible', 'independent', 'individual', 'industry', 'informal', 'injury', 'insect', 'inside', 'instead', 'instruction', 'instructor', 'instrument', 'intelligent', 'international', 'introduction', 'invent', 'invention', 'invitation', 'invite', 'involve', 'item', 'itself', 'jam', 'jazz', 'jewellery', 'joke', 'journalist', 'jump', 'kid',
'kill', 'king', 'knee', 'knife', 'knock', 'knowledge', 'lab', 'lady', 'lake', 'lamp', 'land', 'laptop', 'last', 'later', 'laughter', 'law', 'lawyer', 'lazy', 'lead', 'leader', 'learning', 'least', 'lecture', 'lemon', 'lend', 'less', 'level', 'lifestyle', 'lift', 'light', 'likely', 'link', 'listener', 'little', 'lock', 'look', 'lorry', 'lost', 'loud', 'loudly', 'lovely', 'low', 'luck', 'lucky', 'mail', 'major', 'male', 'manage', 'manager', 'manner', 'mark', 'marry', 'material', 'mathematics', 'maths', 'matter', 'may', 'media', 'medical', 'medicine', 'memory', 'mention', 'metal', 'method', 'middle', 'might', 'mind', 'mine', 'mirror', 'missing', 'mobile', 'monkey',
'moon','mostly', 'motorcycle', 'movement', 'musical', 'musician', 'myself', 'narrow', 'national', 'nature', 'nearly', 'necessary', 'neck', 'need', 'neither', 'nervous', 'network', 'noise', 'noisy', 'none', 'normal', 'normally', 'notice', 'novel', 'nowhere', 'number', 'nut', 'ocean', 'offer', 'officer', 'oil', 'onto', 'opportunity', 'option', 'ordinary', 'organization', 'organize', 'original', 'ourselves', 'outside', 'oven', 'own', 'owner', 'pack', 'pain', 'painter', 'palace', 'pants', 'parking', 'particular', 'pass', 'passenger', 'past', 'patient', 'pattern', 'pay', 'peace', 'penny', 'per', 'per cent', 'perform', 'perhaps', 'permission', 'personality', 'pet', 'petrol', 'photograph', 'physical', 'physics', 'pick', 'pilot', 'planet', 'plant', 'plastic', 'plate', 'platform', 'please', 'pleased', 'pocket', 'polite', 'pollution', 'pop', 'population', 'position', 'possession', 'possibility', 'poster', 'power', 'predict', 'present',
'president','prevent', 'print', 'printer', 'prison', 'prize', 'process', 'produce', 'professional', 'professor', 'profile', 'program', 'progress', 'promise', 'pronounce', 'protect', 'provide', 'pub', 'public', 'publish', 'pull', 'purpose', 'push', 'quality', 'quantity', 'queen', 'question', 'quietly', 'race', 'railway', 'raise', 'rate', 'rather', 'reach', 'react', 'realize', 'receive', 'recent', 'recently',
'reception','recipe', 'recognize', 'recommend', 'record', 'recording', 'recycle','reduce',
'refer', 'refuse', 'region', 'regular', 'relationship', 'remove', 'repair', 'replace', 'reply', 'report', 'reporter', 'request', 'research', 'researcher', 'respond', 'response', 'rest', 'review', 'ride', 'ring', 'rise', 'rock', 'role', 'roof', 'round', 'route', 'rubbish', 'rude', 'run', 'runner', 'running', 'sadly', 'safe', 'sail', 'sailing', 'salary', 'sale', 'sauce', 'save', 'scared', 'scary', 'scene', 'schedule', 'score', 'screen', 'search', 'season', 'seat', 'secondly', 'secret', 'secretary', 'seem', 'sense', 'separate', 'series', 'serious', 'serve', 'service', 'several', 'shake', 'shall',
'shape', 'sheet', 'ship', 'shoulder', 'shout', 'shut', 'side', 'sign', 'silver', 'simple', 'since', 'singing', 'single', 'sir', 'site', 'size', 'ski', 'skiing', 'skin', 'sky', 'sleep', 'slowly', 'smell', 'smile', 'smoke', 'smoking', 'soap', 'soccer', 'social', 'society', 'sock', 'soft', 'soldier', 'solution', 'solve', 'somewhere', 'sort', 'source', 'speaker', 'specific', 'speech','speed',
'spider', 'spoon', 'square', 'stage', 'stair', 'stamp', 'star', 'start', 'state', 'stay', 'steal', 'step', 'stomach','stone',
'store', 'storm', 'straight', 'strange', 'strategy', 'stress', 'structure', 'stupid', 'succeed', 'successful', 'such', 'suddenly', 'suggest', 'suggestion', 'suit', 'support', 'suppose', 'sure', 'surprise', 'surprised', 'surprising', 'survey', 'sweet', 'symbol', 'system', 'tablet', 'talk', 'target', 'task', 'taste', 'teaching', 'technology','teenage',
'temperature', 'term', 'themselves', 'thick', 'thief', 'thin', 'thinking', 'third', 'thought', 'throw', 'tidy', 'tie', 'tip','tool', 'top', 'touch', 'tour', 'tourism', 'towards', 'towel', 'tower', 'toy', 'track', 'tradition', 'traditional', 'train', 'trainer', 'training', 'transport', 'traveller', 'trouble', 'truck', 'twin', 'typical', 'underground', 'understanding', 'unfortunately', 'unhappy', 'uniform', 'unit', 'united', 'unusual', 'upstairs', 'use', 'used to', 'user', 'usual', 'valley', 'van', 'variety', 'vehicle', 'view', 'virus', 'voice', 'wait', 'war', 'wash', 'washing', 'wave', 'weak', 'web', 'wedding','weight', 'welcome', 'wet', 'wheel', 'while', 'whole','whose',
'wide', 'wild', 'wind', 'winner', 'wish', 'wood', 'wooden', 'working', 'worried', 'worry', 'worse', 'worst', 'wow', 'yet', 'yours', 'zero']

turkishWords = ['yetenek [i.]', 'gücü yeten [s.]', 'yurt dışı [i.]', 'kabul etmek [f.]', 'kaza [i.]', 'üzere [ed.]', 'başarmak [f.]', 'hareket etmek [f.]', 'etkin [s.]', 'aslında [zf.]', 'yetişkin kişi [i.]', 'yarar [i.]', 'serüven [i.]', 'ilan etmek [f.]', 'duyuru [i.]', 'ilancılık [i.]', 'gibi davranmak [f.]', 'sonra gelen [s.]', 'ters olarak [zf.]', 'vah [ünl.]', 'havayolu [i.]', 'sağ [s.]', 'hepsi [zm.]', 'yolunda', 'izin vermek [f.]', 'hemen hemen [zf.]', 'yalnız [s.]', 'yanına [zf.]', 'halihazırda [zf.]', 'alternatif [i.]', 'rağmen [bağ.]', 'arasına [ed.]', 'meblağ [i.]', 'antika [s.]', 'öfkeyle [zf.]', 'ayak bileği [i.]', 'her [s.]', 'daha fazla başka [zf.]', 'herhangi biri [i.]', 'her neyse [zf.]', 'herhangi bir yerde [zf.]','uygulama','görünmek [f.]', 'görünüş [i.]', 'uygulamak [f.]', 'tasarlamak [f.]', 'yapı [i.]', 'göstergesi olmak [f.]',
'sav [i.]', 'topluluk [i.]', 'hazırlanmak [f.]', 'düzenleme [i.]', 'dahi [zf.]', 'uyuşuk [s.]', 'yardımcı [s.]', 'sporcu', 'atak [i.]', 'katılmak [f.]', 'ilgi [i.]', 'çekici [s.]', 'izleyici [i.]', 'yazar [i.]', 'mevcut [s.]', 'belirli bir miktar tüketmek [f.]', 'sakınmak [f.]', 'ödül vermek [f.]', 'berbat [s.]', 'sırt [i.]', 'arka plan [i.]', 'berbat bir şekilde [zf.]', 'çubuk [i.]', 'beyzbol [i.]', 'temeli [s.]', 'basketbol [i.]', 'fasulye [i.]', 'taşımak [f.]', 'vurmak [f.]', 'sığır eti [i.]', 'daha önce [zf.]', 'davranmak [f.]', 'davranış [i.]', 'uygun olmak [f.]', 'kemer [i.]', 'çıkar [i.]', 'en iyi [s.]', 'daha iyi [s.]', 'arasında [zf.]','milyar','çöpe atmak [f.]', 'biyoloji [i.]', 'doğum [i.]', 'bisküvi [i.]', 'gemlemek [f.]', 'boşluk [i.]', 'kan [i.]', 'darbe [i.]', 'kurul [i.]', 'kaynamak [f.]',
'kılçıklarını ayıklamak (balık) [f.]', 'kitap [i.]', 'ödünç almak [f.]', 'patron [i.]', 'dip [i.]', 'kase [i.]', 'beyin [i.]', 'köprü yapmak [f.]', 'parlak [s.]', 'muhteşem [s.]', 'kırık [s.]', 'süpürmek [f.]', 'yakmak [f.]', 'işadamı [i.]', 'düğme [i.]', 'kamp [i.]', 'kampçılık [i.]', 'olabilmek [f.]', 'umursamak [f.]', 'özenli [s.]', 'itinayla [zf.]', 'halı [i.]', 'mizah amaçlı çizim yapmak [f.]', 'kılıf [i.]', 'peşin [s.]', 'kale [i.]', 'yakalamak [f.]', 'sebep olmak [f.]', 'kutlamak [f.]', 'ünlü kimse [i.]', 'belli [s.]', 'elbette [zf.]', 'şans [i.]', 'karakter [i.]', 'hayırseverlik [i.]', 'sohbet [i.]', 'kontrol [i.]', 'şef [i.]', 'kimya [i.]', 'takılmak [f.]', 'seçenek [i.]', 'kilise [i.]', 'sigara [i.]', 'çember [i.]', 'klasik [s.]', 'net [s.]', 'açıkça [zf.]',
'zeki [s.]', 'iklim [i.]', 'yakın [s.]', 'kapanmış [s.]', 'giysi [i.]', 'bulut [i.]', 'hazırlamak [f.]', 'deniz kıyısı [i.]', 'şifre [i.]', 'meslektaş [i.]', 'toplamak [f.]', 'sütun [i.]', 'komik olaylar [i.]', 'rahat [s.]', 'yorumlamak [f.]', 'haberleşmek [f.]', 'topluluk [i.]', 'kapışmak [f.]', 'rekabet [i.]', 'şikayet etmek [f.]', 'komple [zf.]', 'koşul [i.]', 'müzakere [i.]', 'bağlanmak [f.]', 'bağlı [s.]', 'durumu değerlendirmek [f.]', 'zaptetmek [f.]', 'içermek [f.]', 'kıta [i.]', 'devam ettirmek [f.]', 'kontrol [i.]', 'yemek pişirmek [f.]', 'ocak [i.]', 'kopyalamak [f.]','köşe [i.]','doğru şekilde [zf.]', 'hesaba katmak [f.]', 'eşleştirmek [f.]', 'kaplamak [f.]', 'çılgın [s.]', 'yaratıcı [s.]', 'kredi [i.]', 'suç [i.]', 'müthiş [s.]', 'karşıya geçmek [f.]', 'kalabalık [i.]', 'kalabalık [s.]','ağlama [i.]', 'dolap [i.]', 'kıvırcık [s.]', 'devir [i.]', 'günlük [s.]', 'tehlike [i.]', 'koyu [s.]', 'veri [i.]', 'ölü [s.]', 'iş yapmak [f.]', 'sevgili [s.]', 'ölüm [i.]', 'karar [i.]', 'derin [s.]', 'elbette [zf.]', 'aşama [i.]', 'dişçi [i.]', 'bölüm [i.]', 'bağlı olmak [f.]', 'çöl [i.]', 'tasarımcı [i.]', 'tahrip etmek [f.]', 'dedektif [i.]', 'geliştirmek [f.]', 'cihaz [i.]', 'günlük [i.]', 'farklı bir biçimde [zf.]', 'dijital [s.]', 'yönetmek [f.]', 'yön [i.]', 'yönetici [i.]', 'aynı düşüncede olmamak [f.]', 'ortadan kaybolmak [f.]', 'felaket [i.]', 'keşfetmek [f.]', 'keşif [i.]', 'tartışma [i.]', 'hastalık [i.]', 'mesafe [i.]', 'boşanmış', 'doküman [i.]', 'iki kat [i.]', 'indirmek [f.]', 'alt kat [i.]', 'dramatik durum [i.]', 'çizim [i.]', 'hayal [i.]', 'sürmek [f.]', 'sürücü [i.]', 'düşüş [i.]',
'ilaç vermek [f.]', 'kurumak [f.]', 'kazanmak [f.]', 'yeryüzü [i.]', 'kolayca [zf.]', 'öğrenim [i.]', 'etki [i.]', 'her iki [s.]', 'elektrik [s.]', 'elektrik [s.]', 'çıngı [i.]', 'elektronik [s.]', 'işe almak [f.]', 'çalışan [i.]', 'işveren [i.]', 'boş [s.]', 'bitiş [i.]', 'enerji [i.]', 'motor [i.]', 'mühendis [i.]', 'kocaman [s.]', 'girmek [f.]', 'çevre [i.]', 'teçhizat [i.]', 'hata [i.]', 'özellikle [zf.]', 'denemek [f.]', 'günlük [s.]', 'her yer [zf.]', 'delil [i.]', 'kesin [s.]', 'tamamen [zf.]', 'mükemmel [s.]', 'dışında [ed.]', 'bulunmak [f.]', 'ümit etmek [f.]', 'deneyim [i.]', 'deney [i.]', 'uzman [i.]', 'açıklama [i.]', 'belli [s.]', 'söz [i.]', 'aşırılık [i.]', 'aşırı [zf.]', 'etmen [i.]', 'imalathane [i.]', 'başarısızlığa uğramak [f.]', 'panayır [i.]', 'düşmek [f.]', 'hayran [i.]', 'çiftlik [i.]',
'çiftçilik [i.]', 'moda [i.]', 'şişmanlatmak [f.]', 'korkmak [f.]', 'özellik [i.]', 'beslemek [f.]', 'kadın [i.]', 'kurgu [i.]', 'alan [i.]', 'kavga etmek [f.]', 'rakam [i.]', 'film [i.]', 'final [i.]', 'en sonunda [zf.]', 'parmak [i.]', 'sona ermek [f.]', 'birinci [s.]', 'ilk olarak [zf.]', 'balık [i.]', 'balık tutma [i.]', 'zinde [s.]', 'tamir etmek [f.]', 'yassı [s.]', 'grip [i.]', 'uçmak [f.]', 'uçma [i.]', 'odak noktası [i.]', 'takip etme [i.]', 'orman [i.]', 'ormanlaştırmak [f.]', 'çatal [i.]', 'resmi [s.]', 'şükür ki [zf.]', 'ileri [s.]', 'bağımsız [s.]', 'taze [s.]', 'buzdolabı [i.]', 'kurbağa [i.]', 'eğlence [i.]', 'mobilya [i.]', 'daha ileri [zf.]', 'gelecek zaman [i.]', 'galeri [i.]', 'açıklık [i.]', 'benzin [i.]', 'kapı [i.]', 'genel [s.]', 'armağan [i.]', 'gol [i.]', 'Allah [i.]', 'altın [i.]',
'golf [i.]', 'güzel [s.]', 'hükümet [i.]', 'çimen [i.]', 'selamlaşmak [f.]', 'zemin [i.]', 'misafir [i.]', 'rehber [i.]', 'silah [i.]', 'adam [i.]', 'alışkanlık [i.]', 'yarım [s.]', 'büyük salon [i.]', 'mutlu bir şekilde [zf.]', 'sahip olmak [f.]', 'baş ağrısı [i.]', 'yürek [i.]', 'sıcaklık [i.]', 'ağır [s.]', 'yükseklik [i.]', 'yardımsever [s.]', 'kahraman [i.]', 'onunki [zm.]', 'dişil kendisi [zm.]', 'saklanmak [f.]', 'yüksek [s.]', 'tepe [i.]', 'kendi [zm.]', 'onunki [zm.]', 'vurmak [f.]',
'hokey','sahip olmak [f.]', 'çukur [i.]', 'ev [i.]', 'ümit etmek [f.]', 'devasa [s.]', 'insanlık [i.]', 'yaralamak [f.]', 'ideal [s.]', 'tanımlamak [f.]', 'hasta [s.]', 'hastalık [i.]', 'imaj [i.]', 'acilen [zf.]', 'olanaksız [s.]', 'dahil edilmiş [s.]', 'kapsama [i.]', 'arttırmak [f.]', 'inanılmaz [s.]', 'özgür [s.]', 'birey [i.]',
'endüstri [i.]', 'resmi olmayan [s.]', 'zarar [i.]', 'böcek [i.]', 'iç taraf [i.]', 'yerine [zf.]', 'talimat [i.]', 'eğitmen [i.]', 'enstrüman [i.]', 'zeki [s.]', 'milletlerarası [s.]', 'giriş [i.]', 'icat etmek [f.]', 'buluş [i.]', 'davet [i.]', 'davet etmek [f.]', 'kapsamak [f.]', 'madde [i.]', 'kendisi [zm.]', 'sıkışmak [f.]', 'caz çalmak [f.]', 'mücevherat [i.]', 'espri yapmak [f.]', 'gazeteci yazar [i.]', 'atlamak [f.]', 'küçük çocuk [i.]', 'öldürme [i.]', 'kral [i.]', 'diz [i.]', 'bıçak [i.]', 'kapıyı vurmak [f.]', 'bilgi [i.]',
'laboratuvar','hanımefendi [i.]', 'göl [i.]', 'ampul [i.]', 'karaya çıkmak [f.]', 'dizüstü bilgisayarı', 'sonuncu [s.]', 'sonraki [zf.]', 'kahkaha [i.]', 'kanun [i.]', 'avukat [i.]', 'tembel [s.]', 'yol göstermek [f.]', 'lider [i.]', 'öğrenim [i.]', 'en az [s.]', 'ders anlatmak [f.]', 'limon [i.]', 'ödünç vermek [f.]',
'daha az şey [i.]', 'seviye [i.]', 'yaşam biçimi [i.]', 'asansör [i.]', 'ışık [i.]', 'büyük ihtimalle [zf.]', 'bağ [i.]', 'dinleyici', 'küçük [s.]', 'kilitlemek [f.]', 'bakış [i.]', 'kamyon [i.]', 'kaybetmek [f.]', 'kaba [s.]', 'yüksek sesle', 'şeker [s.]', 'az [s.]', 'şans [i.]', 'şanslı [s.]', 'posta [i.]', 'başlıca [s.]', 'erkek [i.]', 'yönetmek [f.]', 'yönetici [i.]', 'yol [i.]', 'işaret [i.]', 'evlenmek [f.]', 'malzeme [i.]', 'matematik', 'matematiksel', 'önemli olmak [f.]', 'mayıs ayı [i.]', 'medya [i.]', 'tıbbi [s.]', 'ilaç [i.]', 'bellek [i.]', 'bahsetmek [f.]', 'madde [i.]', 'yöntem [i.]', 'orta yer [i.]', 'mümkün olmak [f.]', 'önemsemek [f.]', 'benimki [zm.]', 'ayna [i.]', 'özlem [i.]', 'mobil [s.]', 'maymun [i.]', 'ay [i.]', 'çoğunlukla [zf.]', 'motosiklet',
'hareket [i.]', 'müzikal [s.]', 'çalgıcı [i.]', 'kendim [zm.]', 'dar [s.]', 'ulusal [s.]', 'tabiat [i.]', 'yaklaşık olarak [zf.]', 'gereken şey [i.]', 'boyun [i.]', 'ihtiyaç duymak [f.]', 'hiçbir [s.]', 'asabi [s.]', 'ağ [i.]', 'gürültü [i.]', 'gürültülü [s.]', 'hiç de [zf.]', 'standart [s.]', 'genelde [zf.]', 'farkına varmak [f.]', 'roman [i.]', 'hiçbir yerde [zf.]', 'sayı [i.]', 'fındık [i.]', 'okyanus [i.]', 'teklif etmek [f.]', 'memur [i.]', 'yağ [i.]', 'üstüne [ed.]', 'fırsat [i.]', 'seçenek [i.]', 'sıradan [s.]', 'organizasyon [i.]', 'hazırlamak [f.]', 'orijinal [s.]', 'biz [zm.]', 'dışarısı [zf.]', 'ocak [i.]', 'sahip olmak [f.]', 'mal sahibi [i.]', 'ambalajlamak [f.]', 'ağrı [i.]', 'boyacı [i.]', 'saray [i.]', 'pantolon [i.]', 'park yapma [i.]', 'özel [s.]', 'geçirmek [f.]', 'yolcu [i.]', 'geçmiş [s.]', 'sabırlı [s.]',
'model [i.]', 'ödemek [f.]', 'barış [i.]', 'sent [i.]', 'her [zf.]','yüzde','rol yapmak [f.]', 'bir ihtimal [zf.]', 'müsaade [i.]', 'kişilik [i.]', 'evcil hayvan [i.]', 'benzin', 'fotoğrafını çekmek [f.]', 'bedensel [s.]', 'fizik', 'gitar penası [i.]', 'pilot [i.]', 'gezegen', 'dikmek [f.]', 'plastik [i.]', 'levha [i.]', 'platform [i.]', 'lütfen [ünl.]', 'memnun olmuş [s.]', 'cep [i.]', 'kibar [s.]', 'kirlilik [i.]', 'patlatmak [f.]', 'nüfus [i.]', 'mevki [i.]', 'mal mülk [i.]', 'ihtimal [i.]', 'afiş [i.]', 'güç [i.]', 'tahmin etmek [f.]', 'sunmak [f.]','başkan [i.]','engel olmak [f.]', 'yazdırmak [f.]', 'yazıcı [i.]', 'hapis [i.]', 'ödül [i.]', 'süreç [i.]', 'üretmek [f.]', 'profesyonel [s.]', 'profesör [i.]', 'profil [i.]', 'programlamak [f.]', 'gelişmek [f.]',
'söz vermek [f.]', 'telaffuz etmek [f.]', 'korumak [f.]', 'sağlamak [f.]', 'meyhane [i.]', 'halk [i.]', 'yayınlamak [f.]', 'hareket etmek [f.]', 'amaç [i.]', 'itelemek [f.]', 'kaliteli [s.]', 'nicelik [i.]', 'kraliçe [i.]', 'soru [i.]', 'sessizce [zf.]', 'yarışmak [f.]', 'tren yolu [i.]', 'büyütmek (çocuk) [f.]', 'oran [i.]', 'oldukça [zf.]', 'ulaşmak [f.]', 'tepki vermek [f.]', 'farkına varmak [f.]', 'teslim almak [f.]', 'yeni (olmuş) [s.]', 'son zamanlarda [zf.]', 'resepsiyon [i.]', 'yemek tarifi [i.]', 'tanımak [f.]', 'tavsiye etmek [f.]', 'kaydetmek [f.]', "kayıt [i.]", 'geri dönüşümünü sağlamak [f.]', 'yerine oturtmak (kırık) [f.]', 'kastetmek [f.]', 'reddetmek [f.]', 'bölge [i.]', 'düzenli [s.]', 'ilişki [i.]', 'kaldırmak [f.]', 'onarım [i.]', 'yer değiştirmek [f.]', 'yanıt [i.]', 'ihbar etmek [f.]', 'muhabir [i.]', 'rica etmek [f.]', 'araştırma yapmak [f.]', 'araştırmacı [i.]', 'yanıtlamak [f.]',
'cevap [i.]', 'dinlenme [i.]', 'gözden geçirmek [f.]', 'binmek [f.]', 'yüzük [i.]', 'doğmak [f.]', 'kaya [i.]', 'rol [i.]', 'çatı [i.]', 'dönmek (köşeyi/virajı) [f.]', 'rota [i.]', 'çöp [i.]', 'kaba [s.]', 'koşmak [f.]', 'yarışçı [i.]', 'koşma [i.]', 'üzüntülü bir şekilde [zf.]', 'güvenilir [s.]', 'yelken [i.]', 'yelken sporu [i.]', 'maaş [i.]', 'satış [i.]', 'terbiyelemek [f.]', 'biriktirmek [f.]','korkmuş [s.]',
'korkutucu [s.]', 'sahne [i.]', 'plan [i.]', 'puan [i.]', 'ekran [i.]', 'araştırma [i.]', 'sezon [i.]', 'oturtmak [f.]','saniyen [zf.]','sır [i.]', 'sekreter [i.]', 'görünmek [f.]', 'algılamak [f.]', 'ayrıştırmak [f.]', 'seri [i.]', 'ciddi [s.]', 'hizmet etmek [f.]', 'servis [i.]', 'çeşitli [s.]', 'sallamak [f.]', 'söz verme durumunda kullanılır [f.]', 'şekil vermek [f.]', 'levha [i.]', 'gemi [i.]', 'omuz [i.]',
'bağırmak [f.]', 'kapalı [s.]', 'kenar [i.]', 'imzalamak [f.]', 'gümüş [s.]', 'sade [s.]', 'o zamandan beri [zf.]', 'uğultu [i.]', 'tek [s.]]', 'efendim [i.]', 'yerleştirmek [f.]', 'büyüklük [i.]', 'kayak yapmak [f.]', 'kayak yapma [i.]', 'cilt [i.]', 'gökyüzü [i.]', 'uyumak [f.]', 'yavaş yavaş [zf.]', 'koklamak [f.]', 'gülümsemek [f.]', 'duman [i.]', 'sigara içme [i.]', 'sabun [i.]','futbol [i.]','sosyal [s.]', 'toplum [i.]', 'çorap [i.]', 'yumuşak [s.]', 'asker [i.]', 'çözüm [i.]', 'çözmek [f.]', 'bir yer [zm.]', 'sıralamak [f.]', 'kaynak [i.]', 'hoparlör [i.]', 'belirli [s.]', 'konuşma [i.]', 'hız [i.]', 'örümcek [i.]', 'kaşık [i.]', 'meydan [i.]', 'sahnelemek [f.]', 'merdiven basamağı [i.]', 'damga [i.]', 'yıldız [i.]', 'başlangıç [i.]', 'belirtmek [f.]', 'kalma [i.]', 'çalmak [f.]', 'üvey [i.]',
'mide [i.]', 'taş [i.]', 'mağaza [i.]', 'fırtına [i.]', 'düz [s.]', 'yabancı [s.]', 'strateji [i.]', 'stres [i.]', 'yapı [i.]', 'aptalca [s.]', 'başarıya ulaşmak [f.]', 'başarılı [s.]', 'böylesine [s.]', 'birdenbire [zf.]', 'önermek [f.]', 'öneri [i.]', 'uygun gelmek [f.]', 'desteklemek [f.]', 'farz etmek [f.]', 'emin [s.]', 'sürpriz [i.]', 'şaşırmış [s.]', 'şaşırtıcı [s.]', 'araştırma [i.]', 'tatlı [i.]', 'sembol [i.]', 'sistem [i.]', 'tablet [i.]', 'konuşma [i.]', 'hedef [i.]', 'görev [i.]', 'tatmak [f.]', 'öğretme [i.]', 'teknoloji [i.]', 'gençlere ait [s.]', 'sıcaklık [i.]', 'isimlendirmek [f.]', 'kendilerine [zm.]', 'kalınlık [i.]', 'hırsız', 'ince [s.]', 'düşünüş [i.]', 'üçüncü olarak [zf.]', 'fikir [i.]', 'fırlatmak [f.]', 'düzenli [s.]', 'bağlamak [f.]', 'bahşiş [i.]', 'araç [i.]',
'üst [i.]', 'dokunmak [f.]', 'tur [i.]', 'turizm', '-e doğru [zf.]', 'havlu [i.]', 'kule [i.]', 'oyuncak [i.]', 'izlemek [f.]', 'gelenek [i.]', 'geleneksel [s.]', 'tren [i.]', 'antrenör [i.]', 'idman [i.]', 'taşımak [f.]', 'yolcu [i.]', 'dert [i.]', 'kamyon [i.]', 'ikiz [i.]', 'özgün [s.]', 'yeraltı [i.]', 'anlayış [i.]', 'maalesef [zf.]', 'mutsuz [s.]', 'üniforma [i.]', 'birim [i.]', 'birleşmiş [s.]', 'alışılmadık [s.]', 'üst kat [i.]', 'kullanma [i.]','alışık [s.]','kullanıcı [i.]', 'olağan [s.]', 'vadi [i.]', 'kamyonet [i.]', 'çeşitlilik [i.]', 'araç [i.]', 'incelemek [f.]', 'virus', 'ses [i.]', 'bekleme [i.]', 'savaş halinde olmak [f.]', 'yıkamak [f.]', 'bulaşık yıkama [i.]', 'dalga [i.]', 'güçsüz [s.]', 'örümcek ağı [i.]', 'nikah [i.]', 'ağırlık [i.]',
'hoş geldiniz [ünl.]', 'ıslak [s.]', 'çark [i.]', 'sırasında [bağ.]', 'tüm [s.]','kimin [zm.]','geniş [s.]', 'yabani [s.]', 'sarmak [f.]', 'kazanan [i.]', 'dilemek [f.]', 'ahşap [i.]', 'ahşap [s.]', 'çalışma [i.]', 'endişeli [s.]', 'endişelenmek [f.]', 'daha kötüsü [i.]', 'en fena [s.]','birisini çok etkilemek ve heyecanlandırmak [f.]','yine de [zf.]', 'sizin [zm.]', 'sıfır [i.]']

while True:
    sayi = rn.randint(0, 865)
    print(englishWords[sayi])
    try:
        giris = str(input("cevabı için q'ya bastıktan sonra enter'a tıklayın :) : "))
        os.system("cls")
        if giris == "q":
            print(englishWords[sayi]+":"+turkishWords[sayi])
        else:
            break
    except KeyboardInterrupt as err:
        print(err)

