import random as rn

englishWord = ["about", "above", "across", "action", "activity", "actor", "actress", "add", "address", "adult", "advice", "afraid", "after", "afternoon", "again", "age", "ago", "agree", "air", "airport", "all", "also", "always", "amazing", "and", "angry", "animal", "another", "answer", "any", "anyone", "anything", "apartment", "apple", "April", "area", "arm", "around", "arrive", "art", "article", "artist", "as", "ask", "at", "August", "aunt", "autumn", "away", "baby", "back", "bad", "bag", "ball", "banana", "band", "bank", "bath", "bathroom", "be", "beach", "beautiful", "because", "become", "bed", "bedroom", "beer", "before", "begin", "beginning", "behind", "believe", "below", "best", "better", "between", "bicycle", "big", "bike", "bill", "bird", "birthday", "black", "blog", "blonde", "blue", "boat", "body", "book", "boot", "bored", "boring", "born", "both", "bottle", "box", "boy", "boyfriend", "bread",
"break","breakfast","bring","brother","brown","build","building","bus","business","busy","but","butter","buy","by","bye","cafe","cake","call","camera","can","cannot","capital","car","card","career","carrot","carry","cat","CD","cent","centre","century","chair","change","chart","cheap","check","cheese","chicken","child","chocolate","choose","cinema","city","class","classroom","clean","climb","clock","close","clothes","club","coat","coffee","cold","college","colour","come","common","company","compare","complete","computer","concert","conversation","cook","cooking","cool","correct","cost","could","country","course","cousin","cow","cream","create","culture","cup","customer","cut","dad","dance","dancer","dancing","dangerous","dark","date","daughter","day","dear","December","decide","delicious","describe","description","design","desk","detail","dialogue","dictionary","die","diet","difference","different","difficult","dinner","dirty","discuss","dish","do","doctor","dog","dollar","door","down",
"downstairs","draw","dress","drink","drive","driver","during","DVD","each","ear","early","east","easy","eat","egg","eight","eighteen","eighty","elephant","eleven","else","email","end","enjoy","enough","euro","even","evening","event","ever","every","everybody","everyone","everything","exam","example","excited","exciting","exercise","expensive","explain","extra","eye","face","fact","fall","FALSE","family","famous","fantastic","far","farm","farmer","fast","fat","father","favourite","February","feel","feeling","festival","few","fifteen","fifth","fifty","fill","film","final","find","fine","finish","fire","first","fish","five","flat","flight","floor","flower","fly","follow","food","foot","football","for","forget","form","forty","four","fourteen","fourth","free","Friday","friend","friendly","from","front","fruit","full","fun","funny","future","game","garden","geography","get","girl","girlfriend","give","glass","go","good","goodbye","grandfather","grandmother","grandparent","great","green","grey","group","grow","guess","guitar","gym","hair","half","hand",
"happen","happy","hard","hat","hate","have","have to","he","head","health","healthy","hear","hello","help","her","here","hey","hi","high","him","his","history","hobby","holiday","home","homework","hope","horse","hospital","hot","hotel","hour","house","how","however","hundred","hungry","husband","I","Internet","ice","ice cream","idea","if","imagine","important","improve","in","include","information","interest","interested","interesting","interview","into","introduce","island","it","its","jacket","January","jeans","job","join","journey","juice","July","June","just","keep","key","kilometre","kind","kitchen","know","land","language","large","last","late","later","laugh","learn","leave","left","leg","lesson","let","letter","library","lie","life","light","like","line","lion","list","listen","little","live","local","long","look","lose","lot","love","lunch","machine","magazine","main","make","man","many","map","March","market","married","match","May","maybe","me","meal","mean","meaning","meat","meet","meeting",
"member", "menu", "message", "metre", "midnight", "mile", "milk", "million", "minute", "miss", "mistake", "model", "modern", "moment", "Monday", "money", "month", "more", "morning", "most", "mother", "mountain", "mouse", "mouth", "move", "movie", "much", "mum", "museum", "music", "must", "my", "name", "natural", "near", "need", "negative", "neighbour", "never", "new", "news", "newspaper", "next", "next to", "nice", "night", "nine", "nineteen", "ninety", "no", "no one", "nobody", "north", "nose", "not", "note", "nothing", "November", "now", "number", "nurse", "object", "o'clock", "October", "of", "off", "office", "often", "oh", "OK", "old", "on", "once", "one", "onion", "online", "only", "open", "opinion", "opposite", "or", "orange", "order", "other", "our", "out", "outside", "over", "own", "page", "paint", "painting", "pair", "paper", "paragraph", "parent", "park", "part", "partner", "party", "passport", "past", "pay", "pen", "pencil", "people", "pepper", "perfect", "period", "person", "personal", "phone", "photo", "photograph", "phrase", "piano", "picture", "piece", "pig", "pink", "place", "plan", "plane", "plant", "play", "player", "please", "point", "police", "policeman", "pool", "poor", "popular", "positive", "possible", "post", "potato", "pound", "practice", "practise",
"prefer","prepare","present","pretty","price","probably","problem","product","programme","project","purple","put","quarter","question","quick","quickly","quiet","quite","radio","rain","read","reader","reading","ready","real","really","reason","red","relax","remember","repeat","report","restaurant","result","return","rice","rich","ride","right","river","road","room","routine","rule","run","sad","salad","salt","same","sandwich","Saturday","say","school","science","scientist","sea","second","section","see","sell","send","sentence","September","seven","seventeen","seventy","share","she","sheep","shirt","shoe","shop","shopping","short","should","show","shower","sick","similar","sing","singer","sister","sit","situation","six","sixteen","sixty","skill","skirt","sleep","slow","small","snake","snow","so","some","somebody","someone","something","sometimes","son","song","soon","sorry","sound","soup","south","space","speak","special","spell","spelling","spend","sport","spring","stand","star","start","statement","station","stay","still","stop","story","street","strong","student","study","style","subject","success","sugar","summer","sun","Sunday","supermarket","sure",
"sweater","swim","swimming","table","take","talk","tall","taxi","tea","teach","teacher","team","teenager","telephone","television","tell","ten","tennis","terrible","test","text","than","thank","thanks","that","the","theatre","their","them","then","there","they","thing","think","third","thirsty","thirteen","thirty","this","thousand","three","through","Thursday","ticket","time","tired","title","to","today","together","toilet","tomato","tomorrow","tonight","too","tooth","topic","tourist","town","traffic","train","travel","tree","trip","trousers","TRUE","try","T-shirt","Tuesday","turn","TV","twelve","twenty","twice","two","type","umbrella","uncle","under","understand","university","until","up","upstairs","us","use","useful","usually","vacation","vegetable","very","video","village","visit","visitor","wait","waiter","wake","walk","wall","want","warm","wash","watch","water","way","we","wear","weather","website","Wednesday","week","weekend","welcome","well","west","what","when","where","which","white","who","why","wife","will","win","window","wine","winter","with","without","woman","wonderful","word","work","worker","world","would","write","writer","writing","wrong","yeah","year","yellow","yes","yesterday","you","young","your","yourself"
]

turkishWord = ["hemen hemen","üzerine","karşıya","çalışma","etkinlik","oyuncu","oyuncu","toplamak","hitap etmek","yetişkin","nasihat","korkmuş","sonra","öğleden sonra","bir daha","yaş","evvel","aynı fikirde olmak","havalandırmak","havalimanı","tüm","ayrıca","hep","şaşırtıcı","ile","kızmış","hayvan","öbür","yanıt vermek","lalettayin","hiç kimse","hiçbir şey","daire","elma","nisan","alan","kol","sularında","varmak","sanat","bent","artist","olarak","soru sormak","üzere","ağustos","hala","güz","uzak",
"yavru", "art", "kötü", "poşet", "balo", "muz", "bant", "banka", "yıkanmak", "tuvalet", "bulunmak", "sahil", "güzel", "çünkü", "haline gelmek", "yatak", "yatak odası", "bira", "evvel", "başlatmak", "başlangıç", "ardındaki", "inanmak", "alttaki", "en iyi", "daha iyi", "arasında", "bisiklet", "iri", "bisiklete binmek", "senet", "kuş", "yaş günü", "siyahi", "web günlüğü", "sarışın", "mavi", "tekne", "ceset", "ayırtmak", "bot", "sıkılmış", "bıktırıcı", "doğan", "her ikisi de", "şişe", "kutu",
"delikanlı","flört","ekmek","kopmak","kahvaltı","getirmek","kardeş","kahverengi","inşa etmek","inşaat","otobüs","işletme","işlek","ancak","tereyağı","ısmarlamak","geçecek biçimde","ast","kafe","kek","çağırmak","fotoğraf makinesi","olabilmek","edememek","sermaye","otomobil","kart","kariyer","kızıl saç","taşımak","kedi","dış çap","sent","merkez","asır","koltuk","değişmek","çizelge","ucuz","denetlemek","peynir","tavuk","evlat","çikolata","seçmek","sinema","kent","ders","sınıf",
"temizlemek","tırmanmak","saat","kapamak","giysi","kulüp","kaplamak","kahve","soğukluk","yüksekokul","renk","gelmek","alışılmış","bölük","mukayese etmek","tamamlamak","bilgisayar","konser","konuşma","yemek pişirmek","yemek pişirme","soğutmak","düzeltmek","mal olmak","-abilirdi","yurt","kurs","kuzen","inek","kaymak","meydana getirmek","kültür","kupa","müşteri","kesmek","babacığım","dans etmek","dansöz","dans etme","tehlikeli","karanlık","çıkmak","kız çocuk","gün","sevgili","aralık (ayı)","karar vermek","nefis","betimlemek",
"tasvir", "dizayn etmek", "çalışma masası", "detay", "diyalog", "sözlük", "ölmek", "diyet", "ayrım", "farklı", "çetin", "akşam yemeği", "pisletmek", "görüşmek", "tabak", "etmek", "doktor", "it", "amerikan parası", "kapı", "aşağıya doğru", "aşağı katta", "karalamak", "giyinmek", "içmek", "sürmek", "sürücü", "zarfında", "dvd", "her biri", "kulak", "erken", "doğu", "rahat", "yemek yemek", "yumurta", "sekiz", "onsekiz", "seksen", "fil", "onbir", "başka", "email göndermek", "sona ermek", "tadını çıkarmak", "kafi", "euro", "düzgün", "akşam", "olay", "durmadan",
"her", "cümle alem", "herkes", "her şey", "imtihan", "örnek", "heyecanlı","heyecanlı", "alıştırma yapmak", "masraflı", "açıklamak", "ekstra", "göz", "yüzleşmek", "vaka", "inmek", "takma", "sülale", "ünlü", "fantastik", "uzak", "çiftlik", "çiftçi", "süratli", "semirtmek", "papaz", "gözde", "şubat", "hissetmek", "his", "bayram", "az", "onbeş", "beşinci", "elli sayısı (50)", "doldurmak", "film", "final", "bulmak", "ceza kesmek", "sona ermek", "ateşlemek", "birinci", "balık", "beş", "düz yüzey", "uçuş", "yeri kaplamak", "çiçek", "uçmak", "takip etmek",
"besin","ayak","futbol","için","unutmak","biçimlendirmek","kırk sayısı (40)","dört","on dört sayısı","dörtte bir","bağımsız","cuma","ahbap","arkadaş canlısı","itibaren","yönelmek","meyve vermek","tok","eğlence","komik","istikbal","oyun","bahçe","coğrafya","elde etmek","kız","kız arkadaş","vermek","kadeh","hareket etmek","güzel","güle güle","dede","babaanne","büyükbaba","mükemmel","yeşil","ağartmak","grup","yetişmek","tahmin etmek","gitarist","spor salonu","tüy","yarım","el","meydana gelmek","sevinçli","çetin","şapka","nefret etmek",
"sahip olmak", "mecburiyetinde kalmak", "erkek", "kelle", "sıhhat", "sıhhatli", "duymak", "merhaba", "yardım etmek", "ona(kız)", "burada", "selam", "merhaba", "yüksek", "ona(erkek)", "eril onunki", "geçmiş", "hobi", "bayram", "ev", "ödev", "ummak", "beygir", "hastane", "kızgın", "otel", "saat", "ev", "nasıl", "bununla birlikte", "yüz", "acıkmış", "koca", "ben", "internet", "buz", "dondurma", "fikir", "eğer", "hayal etmek", "mühim", "geliştirmek", "içeri", "katmak", "bilgi", "ilgilendirmek", "alakalı", "ilginç", "görüşmek", "içine",
"tanıtmak", "ada", "ona", "onun", "ceket", "ocak", "kot", "görev", "birleştirmek", "yolculuk", "meyve suyu", "temmuz", "haziran", "sadece", "tutmak", "anahtar", "kilometre", "tür", "mutfak", "bilmek", "karaya ayak basmak", "lisan", "iri", "sonuncu", "gecikmiş", "sonradan", "gülmek", "öğrenmek", "bırakmak", "sol", "ayak (mobilya/pergel)", "ders", "izin vermek", "mektup", "kitaplık", "yatmak", "yaşam", "aydınlık", "beğenmek", "astarlamak", "aslan", "listelemek", "dinlemek", "ufak", "yaşamak", "lokal", "uzun", "bakmak", "kaybetmek", "pay",
"sevmek","öğle yemeği","dergi","makine","esas","yapmak","insan","birçok","harita","yürüyüş yapmak (topluca)","çarşı","evli","eşleştirmek","mayıs ayı","belki","ben","öğün","demek istemek","mana","et","karşılaşmak","toplantı","üye","menü","ileti","metre","geceyarısı","mil","süt","milyon","dakika","ıska geçmek","yanılgı","model","çağdaş","an","pazartesi","para","ay","daha fazla","sabah","en","ana","dağ","fare","ağız","kımıldamak","film (sinemada gösterilen)",
"fazla", "maske ile oynamak", "müze", "müzik", "gerekmek", "benim", "isim", "tabii", "yakın", "ihtiyaç duymak", "negatif", "komşu", "hiç", "yeni", "haber", "gazete", "sonraki", "bitişik", "sevimli", "gece", "dokuz", "XIX", "doksan sayısı (90)", "hayır", "hiç kimse", "hiç kimse", "kuzey", "burun", "gayri", "not etmek", "hiç", "kasım", "şimdi", "numaralamak", "hemşirelik yapmak", "itiraz etmek", "saat", "ekim", "karşı", "kapalı", "makam", "sık sık", "ey", "onaylamak", "eskimiş", "üstünde", "bir kere", "bir", "soğan", "bağlantılı", "tek",
"açılmak","kanaat","zıt","ya da","portakal","sipariş vermek","öbür","bizim","çıkış","dıştan","bitmiş","sahip olmak","sayfa","boyamak","tablo","çift","kağıt","fıkra","ebeveynlik etmek","park etmek","parça","eş","taraf","geçiş belgesi","geçmiş","ödemek","kalem","kalem","insanlar","biber","kusursuz","devir","kişi","kişisel","telefon etmek","foto","fotoğraflamak","ifade etmek","piyano çalgı","resim","tane","domuz","pembe","koymak","planlamak","düzlemek","dikmek",
"oynamak", "oyuncu", "memnun etmek", "nokta", "polis", "polis", "havuz", "kötü", "popüler", "pozitif", "olabilir", "postalamak", "patates", "yumruklamak", "uygulamak", "pratik yapmak", "tercih etmek", "hazırlamak", "sunmak", "şirin", "bedel", "galiba", "problem", "ürün", "program", "proje", "mor", "koymak", "çeyrek", "soru", "süratli", "hızla", "sessizlik", "epeyce", "radyo", "yağmur yağmak", "okumak", "okur", "okuma", "hazır", "hakiki", "hakikaten", "sebep", "al", "rahatlamak", "hatırlamak", "yinelemek", "haber vermek", "restoran",
"netice", "geri dönmek", "pirinç", "zengin", "binmek", "sağ", "nehir", "yol", "oda", "rutin", "hüküm sürmek", "çalıştırmak", "hüzünlü", "salata", "tuz", "aynı", "sandviç", "cumartesi", "söylemek", "mektep", "ilim", "bilgin", "deniz", "saniye", "kesit", "görmek", "satılmak", "yollamak", "cümle", "eylül", "yedi", "XVII", "yetmiş", "paylaşmak", "dişi hayvan", "koyun", "gömlek", "ayakkabı", "mağaza", "alışveriş", "az", "gerekmek", "göstermek", "sağanak", "hasta", "benzer", "şarkıcı", "abla", "oturmak",
"hal", "şeş", "onaltı", "altmış", "maharet", "etek", "uyumak", "yavaşlatmak", "az", "yılan", "kar", "bu yüzden", "biraz", "biri", "birisi", "bir şey", "bazen", "oğul", "şarkı", "birazdan", "üzgün", "ses", "çorba", "güney", "aralık", "konuşmak", "özel", "hecelemek", "yazım", "geçirmek", "spor", "memba", "geçerli olmak", "yıldız", "başlamak", "ifade", "terminal", "kalmak", "durgun", "durmak", "hikaye", "cadde", "güçlü", "öğrenci", "incelemek", "biçim", "ders", "muvaffakiyet", "şeker", "yaz", "güneş",
"pazar", "süpermarket", "emin", "süveter", "yüzmek", "yüzme", "masa", "almak", "konuşmak", "uzun", "taksi", "çay", "ders vermek", "öğretmen", "takım", "on üç ile on dokuz yaşlar arasındaki", "kimse", "telefon", "televizyon", "haber vermek", "on", "tenis", "berbat", "sınamak", "metin", "-den", "teşekkür etmek", "teşekkür", "şu", "belirli durumlarda isimden önce kullanılır", "tiyatro", "onların", "onlara", "o zamanlar", "oraya", "onlar", "şey", "sanmak", "üçte bir", "susuz", "on üç sayısı (13, XIII)", "otuz sayısı (30, XXX)", "bu", "bin", "iskambilde üçlü", "başından sonuna kadar", "perşembe", "bilet", "kez",
"argın","unvan","karşı","bugün","birlikte","hela","domates","yarın","akşama","gereğinden çok","diş","konu","turist","şehir","gidiş geliş","eğitim vermek","gezmek","ağaç","seyahat","pantolon","hakiki","denemek","tişört","salı","dönmek","televizyon","oniki","yirmi","iki kez","iki","yazmak","şemsiye","dayı","altında","anlayış göstermek","üniversite","ila","yukarı","üst kat","biz","kullanmak","faydalı","genellikle","tatil","sebze","çok","video terminal","köy","ziyaret etmek","ziyaretçi",
"beklemek", "garson", "canlanmak", "yürümek", "duvar", "istemek", "ısıtmak", "yıkanmak", "seyretmek (tv)", "sulamak", "yol", "biz", "giymek", "hava", "internet sitesi", "çarşamba", "hafta", "hafta sonu", "hoş geldiniz", "fışkırmak", "batı", "ne", "ne zaman", "nereye", "hangi", "beyaz", "kimi", "neden", "kocanın eşi", "vasiyet", "kazanmak", "pencere", "şarap sunmak", "kış", "ile", "dış", "kadın", "müthiş", "laf", "çalışmak", "işçi", "alem", "istemek", "yazmak", "yazar", "yazma", "yanlış", "tamam", "yıl", "sarı", "evet",
"dün", "siz", "genç", "senin", "kendiniz"]


while True:
    sayi = rn.randint(0, 897)
    print(englishWord[sayi])
    try:

        giris = str(input("cevabı için q'ya bas"))
        if giris == "q":
            print(englishWord[sayi]+":"+turkishWord[sayi])

        else:
            break
    except KeyboardInterrupt as err:
        print(err)


